name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '1'
        lfs: 'false'
        submodules: 'false'

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: build binaries using vendored deps
      run: |
        go build ./cmd/search

    - name: Run tests
      run: |
        SALES_URL=${{ secrets. SalesURL }} go test -failfast -test.timeout=40s ./...
