name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

    - name: Set up Go 1.23.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        ref: 'master'
        fetch-depth: '1'
        lfs: 'false'
        submodules: 'false'

    - name: Run go vet
      run: |
        go vet ./cmd/... ./internal/... ./tracer/

    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2022.1.1"
        install-go: false

    - name: build binaries using vendored deps
      run: |
        go build -mod=vendor ./cmd/search

    - name: Run tests
      run: |
        export SALES_URL=${{ secrets. SalesURL }}
        go test -short -failfast -test.timeout=40s ./...
