name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

    - name: Set up Go 1.23.x
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: 'master'
        fetch-depth: '1'
        lfs: 'false'
        submodules: 'false'

    - name: Run go vet
      run: |
        go vet ./cmd/... ./internal/... ./tracer/

    - uses: dominikh/staticcheck-action@v1.4.0
      with:
        version: "latest"
        install-go: false

    - name: build binaries using vendored deps
      run: |
        go build -mod=vendor ./cmd/search

    - name: Run tests
      run: |
        export SALES_URL=${{ secrets. SalesURL }}
        go test -short -failfast -test.timeout=40s ./...
