name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Set up Go 1.19.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.4'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        ref: 'master'
        fetch-depth: '1'
        lfs: 'false'
        submodules: 'false'

    - name: Run go vet & static checks
      run: |
        go vet ./cmd/... ./internal/... ./tracer/
        GO111MODULE=on go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
        export PATH=$PATH:$(go env GOPATH)/bin
        staticcheck -debug.version
        staticcheck -go 1.19 ./cmd/... ./internal/... ./tracer/

    - name: build binaries using vendored deps
      run: |
        go build -mod=vendor ./cmd/search

    - name: Run tests
      run: |
        export SALES_URL=${{ secrets. SalesURL }}
        go test -short -failfast -test.timeout=40s ./...
